[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
auto_detect_solc = true
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
gas_price = 1000000000
ast = true
via_ir = true
